spring:
  zipkin:
    baseUrl: http://localhost:9411/

management:
  endpoints:
    enabled: true
    web:
      exposure: 
        include: "*"
  endpoint:
    health:
      show-details: "ALWAYS"

  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    org.springframework.data.*.*: INFO
    org.springframework.cache.*: INFO
    root: INFO
    redis.clients: INFO
    io:
      lettuce:
        core: INFO
