spring:
  profiles:
    include: rabbitmq

rabbitmq:
  service:
    publish:
      url: http://RABBITMQ-PUBLISHER/RABBITMQ-PUBLISHER/sendScheduleMessage

scheduler:
  cron:
    expression: 0 * * * * ?
  fixedrate:
    ms: 15000